routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\ProductControlador;
use App\Http\Controllers\Admin\PromotionControlador;
use App\Http\Controllers\Admin\UserControlador;
use Illuminate\Support\Facades\Route;

Route::get('', [HomeController::class, 'index'])
    ->middleware('can:admin.home')
    ->name('admin.home');
Route::resource('products', ProductControlador::class)
    ->except('show')
    ->names('admin.products');
Route::resource('promotions', PromotionControlador::class)
    ->except('show')
    ->names('admin.promotions');
Route::resource('users', UserControlador::class)
    ->only(['index', 'edit', 'update'])
    ->names('admin.users');
Route::resource('images', ImageController::class)
    ->only(['store','destroy'])
    ->names('admin.images');

routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\WeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('we', [WeController::class, 'index'])->name('we.index');
Route::resource('product', ProductController::class)
    ->only(['index', 'show'])->names('product');
Route::resource('users', ContactController::class)
    ->only(['create', 'store'])->names('contact');
Route::resource('promotions', PromotionController::class)
    ->only(['show'])->names('promotions');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Admin/ProductsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Product;
use Livewire\Component;
use Livewire\WithPagination;

class ProductsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $products = Product::where('name', 'LIKE', '%' . $this->search . '%')
            ->latest('id')
            ->paginate();
        return view('livewire.admin.products-index', compact('products'));
    }
}

app/Http/Livewire/Admin/PromotionsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Promotion;
use Livewire\Component;
use Livewire\WithPagination;

class PromotionsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        $promotions = Promotion::where('name', 'LIKE', '%' . $this->search . '%')
            ->latest('id')
            ->paginate();
        return view('livewire.admin.promotions-index', compact('promotions'));
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        $users = User::where('name', 'LIKE', '%' . $this->search . '%')
            ->orwhere('email', 'LIKE', '%' . $this->search . '%')
            ->paginate();
        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/CommentProductLike.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Product;
use Livewire\Component;

class CommentProductLike extends Component
{

    public Product $product;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.comment-product-like');
    }

    public function modifyILikeProduct($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Product::class);
        } else if (auth()->user()) {
            $this->getStore($id, Product::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->product->refresh();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->product->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Product::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->product->refresh();
        }
    }
}

app/Http/Livewire/ImagesProducts.php
<?php

namespace App\Http\Livewire;

use App\Models\Image;
use Livewire\Component;
use Illuminate\Support\Facades\Storage;

class ImagesProducts extends Component
{

    public $product;

    public function render()
    {
        return view('livewire.images-products');
    }

    public function destroy(Image $image)
    {
        $image->delete();
        Storage::delete($image->url);
        $this->product->refresh();
    }
}

app/Http/Livewire/LikeComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Product;
use Illuminate\Http\Request;
use Livewire\Component;
use Livewire\WithPagination;

class LikeComment extends Component
{

    use WithPagination;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render(Request $request)
    {
        $products = Product::paginate();
        return view('livewire.like-comment', compact('products'));
    }

    public function modifyILikeProduct($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Product::class);
        } else if (auth()->user()) {
            $this->getStore($id, Product::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Product::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
        }
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Navigation extends Component
{
    public function render()
    {
        return view('livewire.navigation');
    }
}

app/Http/Livewire/PromotionCommentLike.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Promotion;
use Livewire\Component;

class PromotionCommentLike extends Component
{
    public Promotion $promotion;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.promotion-comment-like');
    }

    public function modifyILikePromotion($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Promotion::class);
        } else if (auth()->user()) {
            $this->getStore($id, Promotion::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->promotion->refresh();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->promotion->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Promotion::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->promotion->refresh();
        }
    }
}

app/Http/Livewire/SpecialOffers.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Promotion;
use Livewire\Component;

class SpecialOffers extends Component
{
    public $promotions;
    public $commentNew;
    private $idPromotion;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.special-offers');
    }

    public function modifyILikePromotion($id, $isLiked)
    {

        $this->idPromotion = $id;
        if ($isLiked) {
            $this->getDestroy($id, Promotion::class);
        } else if (auth()->user()) {
            $this->getStore($id, Promotion::class);
        }
    }

    public function modifyILikeComment(Comment $comment, $idPromotion)
    {

        $this->idPromotion = $idPromotion;
        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    public function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->promotions->find($this->idPromotion)->refresh();
    }

    public function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->promotions->find($this->idPromotion)->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Promotion::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->promotions->find($id)->refresh();
        }
    }
}

resources/views/livewire/admin/products-index.blade.php
<div class="card">
    <div class="card-header">
        <input type="text" class="form-control" placeholder="Ingrese el titulo del post a buscar..."
            wire:model='search'>
    </div>
    @if ($products->count())
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            NAME
                        </th>
                        <th colspan="2">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <td>{{ $product->id }}</td>
                            <td>{{ $product->name }}</td>
                            @can('admin.products.edit')
                                <td width='10px'>
                                    <a class="btn btn-primary btn-sm" href="{{ route('admin.products.edit', $product) }}">
                                        Editar
                                    </a>
                                </td>
                            @endcan
                            @can('admin.products.destroy')
                                <td width='10px'>
                                    <form action="{{ route('admin.products.destroy', $product) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-sm">Borrar</button>
                                    </form>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $products->links() }}
        </div>
    @else
        <div class="card-body">
            <strong>No se encontro ningun post relacionado con ese post.</strong>
        </div>
    @endif
</div>

resources/views/livewire/admin/promotions-index.blade.php
<div class="card">
    <div class="card-header">
        <input type="text" class="form-control" placeholder="Ingrese el titulo del post a buscar..."
            wire:model='search'>
    </div>
    @if ($promotions->count())
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            NAME
                        </th>
                        <th colspan="2">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($promotions as $promotion)
                        <tr>
                            <td>{{ $promotion->id }}</td>
                            <td>{{ $promotion->name }}</td>
                            @can('admin.promotions.edit')
                                <td width='10px'>
                                    <a class="btn btn-primary btn-sm"
                                        href="{{ route('admin.promotions.edit', $promotion) }}">
                                        Editar
                                    </a>
                                </td>
                            @endcan
                            @can('admin.promotions.destroy')
                                <td width='10px'>
                                    <form action="{{ route('admin.promotions.destroy', $promotion) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-sm">Borrar</button>
                                    </form>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $promotions->links() }}
        </div>
    @else
        <div class="card-body">
            <strong>No se encontro ningun post relacionado con ese post.</strong>
        </div>
    @endif
</div>

resources/views/livewire/admin/users-index.blade.php
<div>
    <div class="card">
        <div class="card-header">
            <input wire:model='search' type="text" class="form-control"
                placeholder="Ingrese el nombre o correo de un usuario" />
        </div>
        @if ($users->count())
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td width='40px'>
                                    <a class="btn btn-primary"
                                        href="{{ route('admin.users.edit', $user) }}">Editar</a>
                                    {{-- <a class="btn btn-danger" href="{{ route('admin.users.destroy', $user) }}"></a> --}}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {{ $users->links() }}
            </div>
        @else
            <div class="card-body">
                <strong>No se encontraron usuarios con ese nombre</strong>
            </div>
        @endif

    </div>
</div>