routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\ProductControlador;
use App\Http\Controllers\Admin\PromotionControlador;
use App\Http\Controllers\Admin\UserControlador;
use Illuminate\Support\Facades\Route;

Route::get('', [HomeController::class, 'index'])
    ->middleware('can:admin.home')
    ->name('admin.home');
Route::resource('products', ProductControlador::class)
    ->except('show')
    ->names('admin.products');
Route::resource('promotions', PromotionControlador::class)
    ->except('show')
    ->names('admin.promotions');
Route::resource('users', UserControlador::class)
    ->only(['index', 'edit', 'update'])
    ->names('admin.users');
Route::resource('images', ImageController::class)
    ->only(['store','destroy'])
    ->names('admin.images');

routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\WeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('we', [WeController::class, 'index'])->name('we.index');
Route::resource('product', ProductController::class)
    ->only(['index', 'show'])->names('product');
Route::resource('users', ContactController::class)
    ->only(['create', 'store'])->names('contact');
Route::resource('promotions', PromotionController::class)
    ->only(['show'])->names('promotions');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Admin/ProductsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Product;
use Livewire\Component;
use Livewire\WithPagination;

class ProductsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $products = Product::where('name', 'LIKE', '%' . $this->search . '%')
            ->latest('id')
            ->paginate();
        return view('livewire.admin.products-index', compact('products'));
    }
}

app/Http/Livewire/Admin/PromotionsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Promotion;
use Livewire\Component;
use Livewire\WithPagination;

class PromotionsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        $promotions = Promotion::where('name', 'LIKE', '%' . $this->search . '%')
            ->latest('id')
            ->paginate();
        return view('livewire.admin.promotions-index', compact('promotions'));
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        $users = User::where('name', 'LIKE', '%' . $this->search . '%')
            ->orwhere('email', 'LIKE', '%' . $this->search . '%')
            ->paginate();
        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/CommentProductLike.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Product;
use Livewire\Component;

class CommentProductLike extends Component
{

    public Product $product;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.comment-product-like');
    }

    public function modifyILikeProduct($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Product::class);
        } else if (auth()->user()) {
            $this->getStore($id, Product::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->product->refresh();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->product->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Product::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->product->refresh();
        }
    }
}

app/Http/Livewire/ImagesProducts.php
<?php

namespace App\Http\Livewire;

use App\Models\Image;
use Livewire\Component;
use Illuminate\Support\Facades\Storage;

class ImagesProducts extends Component
{

    public $product;

    public function render()
    {
        return view('livewire.images-products');
    }

    public function destroy(Image $image)
    {
        $image->delete();
        Storage::delete($image->url);
        $this->product->refresh();
    }
}

app/Http/Livewire/LikeComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Product;
use Illuminate\Http\Request;
use Livewire\Component;
use Livewire\WithPagination;

class LikeComment extends Component
{

    use WithPagination;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render(Request $request)
    {
        $products = Product::paginate();
        return view('livewire.like-comment', compact('products'));
    }

    public function modifyILikeProduct($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Product::class);
        } else if (auth()->user()) {
            $this->getStore($id, Product::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Product::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
        }
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Navigation extends Component
{
    public function render()
    {
        return view('livewire.navigation');
    }
}

app/Http/Livewire/PromotionCommentLike.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Promotion;
use Livewire\Component;

class PromotionCommentLike extends Component
{
    public Promotion $promotion;
    public $commentNew;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.promotion-comment-like');
    }

    public function modifyILikePromotion($id, $isLiked)
    {
        if ($isLiked) {
            $this->getDestroy($id, Promotion::class);
        } else if (auth()->user()) {
            $this->getStore($id, Promotion::class);
        }
    }

    public function modifyILikeComment(Comment $comment)
    {

        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    private function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->promotion->refresh();
    }

    private function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->promotion->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Promotion::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->promotion->refresh();
        }
    }
}

app/Http/Livewire/SpecialOffers.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Like;
use App\Models\Promotion;
use Livewire\Component;

class SpecialOffers extends Component
{
    public $promotions;
    public $commentNew;
    private $idPromotion;

    protected $rules = [
        'commentNew' => 'required|min:3'
    ];

    protected $validationAttributes = [
        'commentNew' => 'comentario'
    ];

    public function render()
    {
        return view('livewire.special-offers');
    }

    public function modifyILikePromotion($id, $isLiked)
    {

        $this->idPromotion = $id;
        if ($isLiked) {
            $this->getDestroy($id, Promotion::class);
        } else if (auth()->user()) {
            $this->getStore($id, Promotion::class);
        }
    }

    public function modifyILikeComment(Comment $comment, $idPromotion)
    {

        $this->idPromotion = $idPromotion;
        if (count($comment->liked())) {
            $this->getDestroy($comment->id, Comment::class);
        } else if (auth()->user()) {
            $this->getStore($comment->id, Comment::class);
        }
    }

    public function getDestroy($id, $class)
    {
        $like =  Like::where('user_id', auth()->user()->id)
            ->where('likeable_id', $id)
            ->where('likeable_type', $class);
        $like->delete();
        $this->promotions->find($this->idPromotion)->refresh();
    }

    public function getStore($id, $class)
    {
        Like::create([
            'likeable_id' => $id,
            'likeable_type' => $class,
            'user_id' => auth()->user()->id
        ]);
        $this->promotions->find($this->idPromotion)->refresh();
    }

    public function saveComment($id)
    {
        if (auth()->user()) {

            $this->validate();

            Comment::create([
                'comment' => $this->commentNew,
                'commentable_id' => $id,
                'commentable_type' => Promotion::class,
                'user_id' => auth()->user()->id
            ]);

            $this->reset('commentNew');
            $this->promotions->find($id)->refresh();
        }
    }
}

resources/views/livewire/comment-product-like.blade.php
<div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
    <span class="text-gray-600 inline-flex items-center leading-none text-2xl float-right -mt-14">
        <button wire:click='modifyILikeProduct({{ $product->id }},{{ count($product->liked()) }})'>

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                class="w-4 h-4 mr-1 @if (count($product->liked())) {{ $colorTexto = 'text-indigo-500' }}
            @else
                {{ $colorTexto = 'text-black' }} @endif">
                <path
                    d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
            </svg>
        </button>
        <p><strong>{{ count($product->likes) }}</strong>
        </p>
    </span>
    <div class="sm:flex sm:items-start">
        <div class="w-full ml-10 mb-4 p-0">
            <div class="w-full bg-none">
                <label for="first_name" class="inline text-xs w-3/12 text-gray-700">
                    Dejar un comentario:
                </label>
                <input type="text" name="first_name" id="first_name" autocomplete="given-name"
                    placeholder="Ingrese un comentario..." wire:model='commentNew'
                    class="inline text-xs w-7/12 bg-gray-200 mt-1 mx-1 p-1 focus:ring-indigo-500 focus:border-indigo-500 focus:bg-white shadow-sm border-gray-600 rounded-md">
                {{-- <div class="px-4 py-3 bg-none text-right sm:px-6"> --}}
                <button type="submit" wire:click='saveComment({{ $product->id }})'
                    class="inline justify-center w-2/12 py-1 px-1 border border-transparent shadow-sm text-xs rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Enviar comentario
                </button>
                {{-- </div> --}}
            </div>
            @error('commentNew') <span class="error">{{ $message }}</span> @enderror
        </div>
    </div>
    <div class="max-h-44 md:max-h-96 overflow-y-auto overflow-x-hidden">
        @foreach ($product->commentsOrderByIdDesc as $comment)
            <div class="pl-3">
                @php
                    $now = new DateTime('today');
                    $christmas = new DateTime($comment->created_at);
                    $interval = $now->diff($christmas);
                @endphp
                <p class="bg-gray-700 py-1 px-2 text-xs text-white">
                    {{ $comment->user->name . ' - Hace ' . $interval->format('%a días') }}
                </p>
                <p class="bg-gray-300 py-2 px-3 text-xs">
                    {{ $comment->comment }}
                </p>
                <span
                    class="text-gray-600 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm px-3 pb-2 border-r-2 border-gray-300 bg-gray-300 w-full">
                    <button wire:click='modifyILikeComment({{ $comment }})'>

                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                            class="w-4 h-4 mr-1 @if (count($comment->liked())) {{ $colorTexto = 'text-indigo-500' }}
                        @else
                            {{ $colorTexto = 'text-black' }} @endif">
                            <path
                                d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                        </svg>
                    </button>
                    <p><strong>{{ count($comment->likes) }}</strong></p>
                </span>
            </div>
        @endforeach
    </div>
</div>

resources/views/livewire/images-products.blade.php
<div class="card-columns">
    @foreach ($product->imageses as $image)
        <div class="card">
            <div class="image-lala">
                <img wire:click='destroy({{ $image }})' class="position-absolute"
                    src="{{ asset('images/cruz.png') }}" style="width: 25px; height: 25px; right:0px;">
            </div>
            <img class="card-img-top" id="picture{{ $image->id }}" src="{{ Storage::url($image->url) }}" alt="">
        </div>
    @endforeach
</div>

resources/views/livewire/like-comment.blade.php
<div class="x-full md:space-y-0 md:grid md:grid-cols-1 lg:grid lg:grid-cols-2 xl:grid-cols-3 md:gap-x-6 md:gap-y-8">
    @foreach ($products as $product)
        <div class="p-4 md:w-full">
            <div class="h-full border-2 border-blue-400 rounded-lg overflow-hidden">
                <img class="lg:h-48 md:h-36 w-full object-cover object-center"
                    src="{{ Storage::url($product->imageses->first()->url) }}" alt="blog">
                <div class="p-6">
                    <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                        {{ trans_choice('messages.products', 1) }}
                    </h2>
                    <h1 class="title-font text-lg font-medium text-gray-900 mb-3">
                        {{ $product->name }}
                    </h1>
                    <p class="leading-relaxed text-xs mb-3 h-40">
                        {!! $product->review !!}
                    </p>
                    <p class="text-center mb-4 pb-2 border-b-2 border-indigo-500">
                        <strong>{{ __('messages.price') }}:</strong>
                        ${{ $product->price }}.-
                    </p>
                    <div class="flex items-center flex-wrap">
                        <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
                            href="{{ route('product.show', $product) }}">
                            {{ __('messages.learn_more') }}
                            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
                                fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M5 12h14"></path>
                                <path d="M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                        <span
                            class="text-gray-600 mr-3 inline-flex items-center ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-300">
                            <button
                                wire:click='modifyILikeProduct({{ $product->id }},{{ count($product->liked()) }})'>

                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                    class="w-4 h-4 mr-1 @if (count($product->liked())) {{ $colorTexto = 'text-indigo-500' }}
                                @else
                                    {{ $colorTexto = 'text-black' }} @endif">
                                    <path
                                        d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                                </svg>
                            </button>
                            <p><strong>{{ count($product->likes) }}</strong></p>
                        </span>
                        <span class="text-gray-600 inline-flex items-center leading-none text-sm"
                            x-data="{ open{{ $product->id }}:false }">
                            <button x-on:click=' open{{ $product->id }} = true '>
                                <svg class="w-4 h-4 mr-1 text-indigo-500" stroke="currentColor" stroke-width="2"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                                    <path
                                        d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z">
                                    </path>
                                </svg>
                            </button>
                            <p><strong>{{ count($product->comments) }}</strong></p>
                            <div class="fixed z-10 inset-0 h-80" x-show='open{{ $product->id }}'>
                                <div
                                    class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                                    <div class="fixed inset-0 transition-opacity" aria-hidden="true">
                                        <div class="absolute inset-0 bg-gray-200 opacity-10"></div>
                                    </div>
                                    <span class="hidden sm:inline-block sm:align-middle sm:h-screen"
                                        aria-hidden="true">&#8203;</span>
                                    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
                                        role="dialog" aria-modal="true" aria-labelledby="modal-headline">
                                        <div class="bg-gray-200 px-4 py-3 sm:px-6 text-center">
                                            <h3><strong>Comentarios</strong></h3>
                                        </div>
                                        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                                            <div class="sm:flex sm:items-start">
                                                <div class="w-full ml-3 mb-4 p-0">
                                                    <div class="w-full bg-none mb-2">
                                                        <label for="first_name"
                                                            class="inline w-3/12 text-xs text-gray-700">
                                                            Dejar un comentario:
                                                        </label>
                                                        <input type="text" name="first_name" id="first_name"
                                                            autocomplete="given-name"
                                                            placeholder="Ingrese un comentario..."
                                                            wire:model='commentNew'
                                                            class="inline text-xs bg-gray-200 mt-1 p-1 w-6/12 focus:ring-indigo-500 focus:border-indigo-500 focus:bg-white shadow-sm border-gray-600 rounded-md">
                                                        <button type="submit"
                                                            wire:click='saveComment({{ $product->id }})'
                                                            class="inline justify-center py-1 px-1 border border-transparent shadow-sm text-xs rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                                            Enviar comentario
                                                        </button>
                                                    </div>
                                                    @error('commentNew')
                                                        <span class="error">
                                                            {{ $message }}
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="max-h-44 md:max-h-96 overflow-y-auto overflow-x-hidden">
                                                @foreach ($product->commentsOrderByIdDesc as $comment)
                                                    <div class="pl-3">
                                                        @php
                                                            $now = new DateTime('today');
                                                            $christmas = new DateTime($comment->created_at);
                                                            $interval = $now->diff($christmas);
                                                        @endphp
                                                        <p class="bg-gray-700 py-1 px-2 text-xs text-white">
                                                            {{ $comment->user->name . ' - Hace ' . $interval->format('%a días') }}
                                                        </p>
                                                        <p class="bg-gray-300 py-2 px-3 text-xs">
                                                            {{ $comment->comment }}
                                                        </p>
                                                        <span
                                                            class="text-gray-600 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm px-3 pb-2 border-r-2 border-gray-300 bg-gray-300 w-full">
                                                            <button
                                                                wire:click='modifyILikeComment({{ $comment }})'>

                                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                                    viewBox="0 0 20 20" fill="currentColor"
                                                                    class="w-4 h-4 mr-1 @if (count($comment->liked())) {{ $colorTexto = 'text-indigo-500' }}
                                                                @else
                                                                    {{ $colorTexto = 'text-black' }} @endif">
                                                                    <path
                                                                        d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                                                                </svg>
                                                            </button>
                                                            <p><strong>{{ count($comment->likes) }}</strong></p>
                                                        </span>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                        <div class="bg-gray-200 px-3 py-2 sm:px-6">
                                            <button type="button" x-on:click=' open{{ $product->id }} = false '
                                                class="mt-3 w-full justify-center rounded-md border border-green-700 shadow-sm px-2 py-1 bg-green-300 text-xs text-gray-700 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
                                                Cerrar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
</div>